### ISSUE TITLE
javaBeanReduceCDH 编译报错

### ISSUE THREAD

**Issue by penger** [javaxsky/cdhproject#1]
[https://github.com/javaxsky/cdhproject/blob/master/mrdemo/src/main/java/com/cloudera/BeanReduceCDH.java](BeanReduceCDH)
这个类，导入Idea 报错 ，编译不通过
不是很理解为什么要这么写

`public class BeanAndFile.java
		LoginUtil.java
		RemoteHadoopUtil.javaBeanReduceCDH extends Reducer<Text,IntWritable,Text, IntWritable> {}`

**Comment by javaxsky** [comment]
再更新下代码吧，这个是之前提交把多余的代码提交上去了
